[tool.poetry]
name = "pictollms"
version = "0.1.0"
description = ""
authors = ["Robin Kokot <robin.edu.hr@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
